apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: best-app
  template:
    metadata:
      labels:
        app: best-app
    spec:
      containers:
      - name: best-app
        image: gospelmike/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: best-app-svc
spec:
  selector:
    app: best-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
